import type { Metadata } from "next";

import "./globals.css";
import { ReactNode } from "react";
import { inter, plexMono } from "@/lib/constants";

import { Providers } from "@/components/providers/Providers";
import { Toaster } from "@/components/ui/sonner";
import "allotment/dist/style.css";
export const metadata: Metadata = {
  title: "Cursor Clone",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${plexMono.variable} antialiased`}
      >
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
};
export default RootLayout;
